/* 判断题题库（共 80 题）— 老师模拟卷 + 补充练习 */
const JUDGE_BANK = [
  // ========== 老师模拟题（10 题）==========
  {q:"HTML 的标签 ol 用于创建无序列表。（ ）",a:false,e:"错误。<ol> 是 ordered list 有序列表，带数字编号；无序列表应使用 <ul>。记忆：ol 有序，ul 无序，看首字母 o/u。"},
  {q:"在 HTML 表格中，表格的列数等于任意一行中 th 与 td 标签的个数。（ ）",a:true,e:"正确。规范表格每行单元格数量一致，一行中 th 与 td 的总数即列数。若 rowspan/colspan 合并需按实际网格理解，标准题默认每行相等。记忆：数一行有几个格就是几列。"},
  {q:"将 input 标签的 type 属性设置为 checkbox 可以生成复选框控件，一组复选框允许同时选多个。（ ）",a:true,e:"正确。checkbox 复选框可多选；同 name 的 radio 才只能单选。记忆：check 可打多个勾，radio 只能选一个。"},
  {q:"相邻兄弟选择器可选择紧接在另一元素后的元素，且二者有相同父元素。（ ）",a:true,e:"正确。相邻兄弟选择器 A + B 选中紧接在 A 之后、与 A 同父元素的 B。记忆：加号 + 表示「紧挨着的弟弟」。"},
  {q:"CSS 中的 color 属性用于设置 HTML 元素的背景颜色。（ ）",a:false,e:"错误。color 设置文字（前景）颜色；背景色用 background-color。记忆：color 管字，background 管底。"},
  {q:"CSS 属性 opacity 如果设置为 1，表示完全透明。（ ）",a:false,e:"错误。opacity:1 表示完全不透明；0 才是完全透明，0.5 半透明。记忆：opacity 越大越实，1 最实，0 全透。"},
  {q:"在CSS盒模型中，width和height属性指的是内容区域的宽度和高度。（ ）",a:true,e:"正确。默认 content-box 下 width/height 指 content 内容区，不含 padding、border（border-box 时含内边距和边框）。记忆：默认宽高只管内容区。"},
  {q:"textContent 和 innerHTML 都可用于设置或返回节点的文本内容，二者功能相同。（ ）",a:false,e:"错误。innerHTML 会解析 HTML 标签；textContent 只处理纯文本，标签会被当作文字。记忆：要解析 HTML 用 innerHTML，只要纯文字用 textContent。"},
  {q:"任何标签都可以通过加 style 属性来直接定义它的样式。（ ）",a:true,e:"正确。内联 style 属性可作用于几乎所有 HTML 元素，优先级也很高。记忆：style 属性 = 内联样式，直接写在标签上。"},
  {q:"要在 HTML 中显示一个尖括号\"<\"，需要用到字符实体是&nbsp;。（ ）",a:false,e:"错误。显示 < 应使用 &lt;；&nbsp; 是不换行空格。记忆：lt = less than 小于号，gt 大于号，nbsp 空格。"},
  // ========== 补充练习（70 题）==========
  {q:"HTML 中 <ul> 标签用于创建无序列表。（ ）",a:true,e:"正确。<ul> 是 unordered list，列表项前通常为圆点；有序列表用 <ol>。记忆：ul 无序，ol 有序。"},
  {q:"HTML5 文档在开头声明 <!DOCTYPE html> 有助于浏览器以标准模式解析页面。（ ）",a:true,e:"正确。DOCTYPE 告知浏览器文档类型，避免怪异模式。HTML5 写法简洁为 <!DOCTYPE html>。记忆：DOCTYPE 开头一行，标准模式靠它。"},
  {q:"<meta charset=\"UTF-8\"> 必须写在 <body> 内才能生效。（ ）",a:false,e:"错误。charset 声明应放在 <head> 内且尽量靠前，以便尽早确定编码。记忆：meta charset 放 head，别放 body。"},
  {q:"<title> 标签中的文字会显示在浏览器标签页标题栏上。（ ）",a:true,e:"正确。<title> 定义文档标题，显示于标签页；<h1> 是页面内可见标题。记忆：title 给浏览器看，h1 给用户看。"},
  {q:"<img> 标签必须写成 <img></img> 成对闭合形式才合法。（ ）",a:false,e:"错误。<img> 是空元素/单标签，不需要也不应写闭合标签。记忆：img、br、hr、input 等常见单标签。"},
  {q:"<link rel=\"stylesheet\" href=\"style.css\"> 引入的外部 CSS 内容会直接显示在页面上。（ ）",a:false,e:"错误。link 引入的样式表只作用于页面样式，不会在页面上显示 CSS 文本。记忆：link 是引用，不是把文件内容贴到页面。"},
  {q:"表单的 action 属性用于指定提交数据发送到的目标地址。（ ）",a:true,e:"正确。action 是表单提交的 URL；method 指定 GET/POST 方式。记忆：action 去哪交，method 怎么交。"},
  {q:"input 的 placeholder 属性值会在表单提交时作为字段值发送到服务器。（ ）",a:false,e:"错误。placeholder 只是灰色提示，不是实际值；未输入时不会代替 value 提交。记忆：placeholder 提示用，value 才是值。"},
  {q:"设置了 disabled 属性的表单控件不会随表单一起提交。（ ）",a:true,e:"正确。disabled 禁用控件不参与提交；readonly 只读但仍会提交。记忆：disabled 不提交，readonly 还提交。"},
  {q:"设置了 readonly 的文本框用户不能编辑，但提交时仍会发送其 value。（ ）",a:true,e:"正确。readonly 只读不可改，值仍随表单提交；disabled 才禁用且不提交。记忆：只读还能交，禁用不能交。"},
  {q:"HTML5 中 <nav> 标签语义上表示页面中的导航链接区域。（ ）",a:true,e:"正确。<nav> 专门表示主要导航区块，比 div 更有语义。记忆：nav = navigation 导航。"},
  {q:"一个 HTML 页面中 <header> 标签最多只能出现一次。（ ）",a:false,e:"错误。HTML5 允许多个 header，例如每篇文章都可有自己的 header。记忆：header 可多个，main 通常一个。"},
  {q:"<article> 适合包裹一篇可以独立阅读、独立分发的新闻或博客正文。（ ）",a:true,e:"正确。<article> 表示独立完整的内容单元。记忆：article = 一篇完整文章。"},
  {q:"表格单元格的 colspan 属性用于横向跨列合并单元格。（ ）",a:true,e:"正确。colspan 跨列，rowspan 跨行。记忆：col 列 span 跨，row 行 span 跨。"},
  {q:"<textarea> 控件用于输入多行文本内容。（ ）",a:true,e:"正确。textarea 多行文本；input type=\"text\" 是单行。记忆：textarea = 文本区域，多行。"},
  {q:"同一 HTML 页面中，多个元素可以使用相同的 id 属性值。（ ）",a:false,e:"错误。id 在页面中应唯一；重复 id 会导致 getElementById 等行为异常。class 才可重复使用。记忆：id 唯一，class 可重复。"},
  {q:"HTML 注释的正确语法是 <!-- 注释内容 -->。（ ）",a:true,e:"正确。HTML 注释以 <!-- 开头、--> 结尾，内容不会显示在页面上。记忆：尖括号叹号减减，注释藏中间。"},
  {q:"在 <html lang=\"zh-CN\"> 中设置 lang 属性对无障碍访问和 SEO 有帮助。（ ）",a:true,e:"正确。lang 声明页面语言，屏幕阅读器和搜索引擎会利用它。记忆：lang = language 语言标识。"},
  {q:"使用 GET 方式提交表单时，数据会以查询字符串形式附加在 URL 后面。（ ）",a:true,e:"正确。GET 把 name=value 拼到 URL；POST 放在请求体。记忆：GET 看地址栏，POST 看请求体。"},
  {q:"同一 name 的一组 <input type=\"radio\"> 单选按钮可以同时选中多个。（ ）",a:false,e:"错误。radio 同组只能选一个；checkbox 才允许多选。记忆：radio 单选，checkbox 多选。"},
  {q:"<select> 下拉框内部需要使用 <option> 标签来定义各个选项。（ ）",a:true,e:"正确。select 包裹 option，option 的 value 是提交值。记忆：select 选框，option 选项。"},
  {q:"<figure> 常与 <figcaption> 配合，为图片或图表添加说明文字。（ ）",a:true,e:"正确。figure 装插图，figcaption 写图注。记忆：figure 图，figcaption 图注。"},
  {q:"HTML 字符实体 &gt; 用于在页面中显示大于号 >。（ ）",a:true,e:"正确。&gt; 表示 >，&lt; 表示 <，避免被解析成标签。记忆：gt 大于，lt 小于。"},
  {q:"CSS 类选择器以英文句点 . 开头，例如 .menu。（ ）",a:true,e:"正确。类选择器 .className；ID 用 #，元素直接用标签名。记忆：点 class，井 id。"},
  {q:"CSS 中 margin 指的是元素边框以外的外边距。（ ）",a:true,e:"正确。margin 在 border 外侧；padding 在 border 内侧。记忆：margin 外边距，padding 内边距。"},
  {q:"设置 box-sizing: border-box 后，元素的 width 会包含 padding 和 border。（ ）",a:true,e:"正确。border-box 把 padding、border 算进 width；content-box 则不算。记忆：border-box 边框算进宽。"},
  {q:"display: flex 可以将元素设置为 Flex 弹性盒子容器。（ ）",a:true,e:"正确。父元素 display:flex 后，子元素成为 flex 项目。记忆：想弹性布局，父元素写 flex。"},
  {q:"Flex 布局中 justify-content 控制项目在主轴方向上的对齐方式。（ ）",a:true,e:"正确。justify-content 管主轴；align-items 管交叉轴。记忆：justify 主轴，align 交叉轴。"},
  {q:"CSS 伪类 :visited 可用于设置用户已访问过的链接样式。（ ）",a:true,e:"正确。:visited 匹配已访问链接，常与 :link、:hover 配合。记忆：visited = 已访问。"},
  {q:"内联 style 属性的优先级通常高于外部样式表中的类选择器。（ ）",a:true,e:"正确。优先级大致为：内联 > ID > 类 > 元素。记忆：越靠近元素优先级越高，内联最近。"},
  {q:"CSS 单位 em 相对于当前元素父元素的 font-size 计算。（ ）",a:true,e:"正确。1em 等于父元素 font-size；rem 相对根元素 html。记忆：em 看爹，rem 看根。"},
  {q:"position 为默认值 static 时，设置 z-index 仍然有效。（ ）",a:false,e:"错误。z-index 只对 position 非 static 的元素生效。记忆：要叠层先定位，static 叠不了。"},
  {q:"position: fixed 的元素相对于浏览器视口（viewport）定位。（ ）",a:true,e:"正确。fixed 相对视口固定，滚动不移动；absolute 找定位祖先。记忆：fixed 钉窗口，absolute 找祖先。"},
  {q:"visibility: hidden 的元素不再占据页面布局空间。（ ）",a:false,e:"错误。visibility:hidden 不可见但仍占位；display:none 才不占位。记忆：hidden 隐身占位，none 消失不占位。"},
  {q:"display: none 的元素不会在页面上占据布局空间。（ ）",a:true,e:"正确。display:none 不参与布局渲染；visibility:hidden 仍占位。记忆：none 不占位，hidden 还占位。"},
  {q:"CSS transition 属性通常可以对 display 实现平滑的渐变过渡效果。（ ）",a:false,e:"错误。display 是离散属性，无法平滑过渡；颜色、透明度等可以。记忆：display 只有跳变，不能渐变。"},
  {q:"animation-iteration-count 属性用于设置 CSS 动画重复播放的次数。（ ）",a:true,e:"正确。iteration-count:3 播放 3 次；infinite 无限循环。记忆：iteration = 重复次数。"},
  {q:"Flex 容器默认的 flex-direction 值为 row（水平方向）。（ ）",a:true,e:"正确。默认 row 水平从左到右；column 才垂直。记忆：row 横，column 竖。"},
  {q:"CSS 后代选择器 div p 表示选中 div 内部所有的 p 元素。（ ）",a:true,e:"正确。空格表示后代；div>p 才是直接子元素。记忆：有空格 = 里面所有，有 > = 直接儿子。"},
  {q:"子选择器 div > p 与后代选择器 div p 在任何情况下选中的元素都相同。（ ）",a:false,e:"错误。div p 选所有后代 p；div>p 只选直接子 p，范围不同。记忆：> 只选亲儿子，空格选子孙。"},
  {q:"伪元素 ::before 要产生可见内容，通常必须设置 content 属性。（ ）",a:true,e:"正确。::before/::after 无 content 往往不显示生成内容。记忆：伪元素没 content 就不现身。"},
  {q:"CSS @media 规则常用于根据屏幕尺寸等条件实现响应式布局。（ ）",a:true,e:"正确。@media 即媒体查询，如 @media (max-width:768px)。记忆：media = 看设备条件换样式。"},
  {q:"CSS 中 font-color 是 W3C 标准规定的文字颜色属性名。（ ）",a:false,e:"错误。文字颜色标准属性是 color，没有 font-color。记忆：文字 color，背景 background-color。"},
  {q:"JavaScript 中 var 声明的变量具有块级作用域。（ ）",a:false,e:"错误。var 是函数作用域（或全局），会变量提升；块级作用域用 let/const。记忆：var 函数级，let/const 块级。"},
  {q:"使用 innerHTML 赋值时，字符串中的 HTML 标签会被浏览器解析并渲染。（ ）",a:true,e:"正确。innerHTML 会解析 HTML；textContent 则当纯文本。记忆：innerHTML 解析，textContent 纯文本。"},
  {q:"HTML 中 <hr> 标签属于行内元素，不会独占一行。（ ）",a:false,e:"错误。<hr> 是块级元素，会独占一行显示水平线；行内如 span、a。记忆：hr 块级换行，span 行内不换。"},
  {q:"Flex 布局中 flex-direction 的默认值是 column（垂直方向）。（ ）",a:false,e:"错误。默认是 row 水平排列；column 需显式设置。记忆：默认 row 横排，column 要手写。"},
  {q:"document.getElementsByClassName() 返回匹配的第一个元素对象。（ ）",a:false,e:"错误。它返回 HTMLCollection 集合，可能含多个元素；getElementById 才返回单个。记忆：ByClassName 集合，ById 单个。"},
  {q:"CSS 通配符选择器 * 表示选中页面中 id 属性值为 * 的元素。（ ）",a:false,e:"错误。* 是通配符，匹配所有元素；选 id 用 #id。记忆：* 全选，# 选 id。"},
  {q:"JavaScript 数组最后一个元素的下标等于 arr.length。（ ）",a:false,e:"错误。下标从 0 开始，最后一个下标是 arr.length - 1。记忆：长度比最大下标大 1。"},
  {q:"HTML 的 onclick 属性与 addEventListener 一样，可以为同一事件绑定多个处理函数且互不覆盖。（ ）",a:false,e:"错误。onclick 属性后者覆盖前者；addEventListener 可叠加多个监听。记忆：addEventListener 能叠，onclick 会覆盖。"},
  {q:"<strong> 与 <b> 标签在语义和功能上完全相同，没有任何区别。（ ）",a:false,e:"错误。strong 语义强调「重要」，b 主要是视觉加粗。记忆：strong 有语义，b 偏样式。"},
  {q:"使用 POST 方式提交表单时，数据一定会显示在浏览器地址栏中。（ ）",a:false,e:"错误。POST 数据在请求体，不在 URL；GET 才会出现在地址栏。记忆：POST 藏体内，GET 露 URL。"},
  {q:"CSS 单位 em 是相对于根元素 html 的 font-size 计算的。（ ）",a:false,e:"错误。em 相对父元素 font-size；rem 才相对根元素 html。记忆：em 看父，rem 看根，别混。"},
  {q:"position: absolute 的元素始终相对于 body 元素定位。（ ）",a:false,e:"错误。absolute 相对最近 position 非 static 的祖先；都不满足时才到初始包含块。记忆：absolute 找定位祖先，不是总找 body。"},
  {q:"JavaScript 中 == 运算符在比较时永远不会进行类型转换。（ ）",a:false,e:"错误。== 会先类型转换再比较；=== 才严格不转换。记忆：双等会转换，三等不转换。"},
  {q:"JavaScript 中 let 声明的变量具有块级作用域。（ ）",a:true,e:"正确。let/const 在 {} 块内有效；var 是函数作用域。记忆：let 块级，var 函数级。"},
  {q:"JavaScript 中 const 声明的常量绑定后不能重新赋值为另一个值。（ ）",a:true,e:"正确。const 不能重新赋值；let/var 可以。记忆：const 常量，赋值一次不能改。"},
  {q:"JavaScript 运算符 === 在比较时会同时比较值和数据类型。（ ）",a:true,e:"正确。=== 严格相等，类型不同直接 false。记忆：三等比类型，双等会转换。"},
  {q:"typeof null 的返回值是字符串 \"null\"。（ ）",a:false,e:"错误。typeof null 返回 \"object\"，这是 JS 历史遗留问题。记忆：typeof null 是 object，别记成 null。"},
  {q:"JavaScript 数组元素的下标从 0 开始。（ ）",a:true,e:"正确。第一个元素 arr[0]，最后一个 arr[arr.length-1]。记忆：数组从 0 数，不是从 1。"},
  {q:"arr.push(x) 会将元素 x 添加到数组末尾。（ ）",a:true,e:"正确。push 末尾添加；pop 末尾删除；unshift/shift 操作开头。记忆：push 尾部进，pop 尾部出。"},
  {q:"arr.slice() 方法不会修改原数组，而是返回新数组片段。（ ）",a:true,e:"正确。slice 不改动原数组；splice 会修改原数组。记忆：slice 切片不改，splice 剪接会改。"},
  {q:"document.getElementById() 返回匹配 ID 的单个元素对象。（ ）",a:true,e:"正确。getElementById 返回单个 Element 或 null。记忆：ById 一个，ByName/ByTagName 集合。"},
  {q:"event.preventDefault() 可以阻止元素的默认行为（如链接跳转、表单提交）。（ ）",a:true,e:"正确。preventDefault 阻止默认；stopPropagation 阻止冒泡。记忆：prevent 拦默认，stop 拦冒泡。"},
  {q:"JSON.parse() 可以将符合 JSON 格式的字符串解析为 JavaScript 对象。（ ）",a:true,e:"正确。parse 字符串→对象；stringify 对象→字符串。记忆：parse 解析进 JS，stringify 序列化出去。"},
  {q:"JavaScript 表达式 NaN === NaN 的结果是 true。（ ）",a:false,e:"错误。NaN 不等于任何值包括自身，NaN === NaN 为 false，需用 isNaN() 判断。记忆：NaN 谁都不等，包括自己。"},
  {q:"JavaScript 表达式 null == undefined 的结果是 true。（ ）",a:true,e:"正确。== 下 null 与 undefined 相等；=== 则 false（类型不同）。记忆：双等 null 约等于 undefined。"},
  {q:"setTimeout(fn, 1000) 设置的函数只会执行一次。（ ）",a:true,e:"正确。setTimeout 延迟一次；setInterval 才重复执行。记忆：Timeout 一次，Interval 循环。"},
  {q:"DOMContentLoaded 事件通常比 window.onload 更早触发。（ ）",a:true,e:"正确。DOMContentLoaded 在 DOM 解析完即触发；load 需等图片等资源。记忆：DOM 好了先 DOMContentLoaded，全加载完才 load。"}
];
